site_name: PyPUMS
theme: readthedocs

nav:
  - PyPUMS: index.md
  - User guide:
    - Installation: user-guide/installation.md
    - Usage: user-guide/usage.md
  - API reference: 
    - Surveys (ACS): reference/surveys.md
    - CLI: reference/cli.md
  - About:
    - Authors: about/authors.md
    - Contributing: about/contributing.md
    - Changelog: about/history.md

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
            show_root_heading: true
  
markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists
    - admonition
    - codehilite
    - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ''
    - pymdownx.tabbed:
        alternate_style: true
    - mdx_include
    - mkdocs-typer
