site_name: PyPUMS
theme: readthedocs
plugins:
  - search
  
markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists
    - admonition
    - codehilite
    - mkautodoc
    - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ''
    - pymdownx.tabbed:
        alternate_style: true
    - mdx_include